// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aGate.Models;

#nullable disable

namespace aGate.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251124143658_database")]
    partial class database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aGate.Models.Campaing", b =>
                {
                    b.Property<int>("campaingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("campaingID"));

                    b.Property<int>("campaingBudget")
                        .HasColumnType("int");

                    b.Property<DateTime>("campaingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("campaingEstimatedPrice")
                        .HasColumnType("int");

                    b.Property<string>("campaingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("campaingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("campaingStatus")
                        .HasColumnType("int");

                    b.HasKey("campaingID");

                    b.ToTable("campaings");
                });

            modelBuilder.Entity("aGate.Models.CampaingStaff", b =>
                {
                    b.Property<int>("CampaingStaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampaingStaffID"));

                    b.Property<int>("CampaingID")
                        .HasColumnType("int");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("CampaingStaffID");

                    b.HasIndex("CampaingID");

                    b.HasIndex("StaffID");

                    b.ToTable("CampaingStaffs");
                });

            modelBuilder.Entity("aGate.Models.Client", b =>
                {
                    b.Property<int>("clientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientID"));

                    b.Property<string>("clientAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientPhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("clientID");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("aGate.Models.Staff", b =>
                {
                    b.Property<int>("staffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staffID"));

                    b.Property<string>("staffContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staffID");

                    b.ToTable("staffs");
                });

            modelBuilder.Entity("aGate.Models.StaffNote", b =>
                {
                    b.Property<int>("NoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoteID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffNotes");
                });

            modelBuilder.Entity("aGate.Models.CampaingStaff", b =>
                {
                    b.HasOne("aGate.Models.Campaing", "Campaing")
                        .WithMany("CampaingStaffs")
                        .HasForeignKey("CampaingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aGate.Models.Staff", "Staff")
                        .WithMany("CampaingStaffs")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaing");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("aGate.Models.StaffNote", b =>
                {
                    b.HasOne("aGate.Models.Staff", "Staff")
                        .WithMany("Notes")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("aGate.Models.Campaing", b =>
                {
                    b.Navigation("CampaingStaffs");
                });

            modelBuilder.Entity("aGate.Models.Staff", b =>
                {
                    b.Navigation("CampaingStaffs");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
